---
driver:
  name: azurerm
  azure_resource_group_prefix: kitchen-<%= ENV['USER'] %>-
  resource_group_tags: &tags
    X-Contact: <%= ENV['USER'] %>
    X-Application: <%= ENV['X_APPLICATION'] %>
    X-Dept: <%= ENV['X_DEPT'] %>
    X-Customer: "Test-Kitchen"
    X-Project: "Test-Kitchen"
    X-TTL: 4
  vm_tags: *tags

driver_config:
  subscription_id: <%= ENV['AZURE_SUBSCRIPTION_ID'] %>
  location: <%= ENV['AZURE_LOCATION'] %>
  machine_size: 'Standard_D2_v2'

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  max_retries: 10
  wait_for_retry: 180
verifier:
  name: inspec

platforms:
  - name: windows-2016
    driver_config:
      image_urn: MicrosoftWindowsServer:WindowsServer:2016-Datacenter:latest
    transport:
      name: winrm
      elevated: true
      operation_timeout: 240

suites:
  - name: default
    run_list:
      - recipe[cis-baseline::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
