name 'cis-baseline'
maintainer 'James Massardo'
maintainer_email 'james@dxrf.com'
license 'All Rights Reserved'
description 'Installs/Configures cis-baseline'
version '0.2.13'
supports 'ubuntu'
issues_url 'https://github.com/jmassardo/cis-baseline/issues'
source_url 'https://github.com/jmassardo/cis-baseline'
